module TogglRb
  module Core
    class Projects < Base
      def search: (untyped workspace_id, ?::Hash[untyped, untyped] query_params) -> untyped

      def create: (untyped workspace_id, untyped project_attributes) -> untyped
    end
  end
end
