module TogglRb
  module Core
    class TimeEntries < Base
      def get: (Integer time_entry_id, ?Hash[untyped, untyped] query_params) -> untyped

      def list: (Hash[untyped, untyped] query_params) -> Array[untyped]

      def create: (untyped workspace_id, attributes time_entry_attributes) -> untyped

      def patch: (string_or_int workspace_id, Array[Integer] time_entries, TogglRb::JSONPatch operation) -> untyped

      def delete: (string_or_int workspace_id, string_or_int time_entry_id) -> bool

      def update: (string_or_int workspace_id, string_or_int time_entry_id, ?Hash[untyped, untyped] request_params) -> untyped
    end
  end
end
