module TogglRb
  module Core
    class Users
      include EndpointDSL
      extend EndpointDSL::ClassMethods

      def list: (untyped workspace_id) -> untyped

      private

      def send_request: (untyped request_method, untyped resource_path, untyped body) -> untyped

      def connection: () -> untyped
    end
  end
end
