module TogglRb
  class Client
    @core_connection: untyped

    @reports_connection: untyped

    attr_reader core_connection: untyped

    attr_reader reports_connection: untyped

    URLS: { core: { url: "https://api.track.toggl.com/api/v9" }, reports: { url: "https://api.track.toggl.com/reports/api/v3/" } }

    def initialize: () -> void

    private

    def config: () -> TogglRb::Config
  end
end
