module TogglRb
  class Client
    @core_connection: Connection

    @reports_connection: Connection

    attr_reader core_connection: Connection

    attr_reader reports_connection: Connection

    def initialize: () -> void

    private

    def config: () -> TogglRb::Config
  end
end
