module TogglRb
  module RequestHelpers
    def send_request: (Symbol request_method, String resource_path, ?untyped? body, ?Hash[untyped, untyped] request_options) -> untyped

    private 

    def connection: () -> TogglRb::Connection

    def request_all: (TogglRb::Response response) -> Array[Response]

    def handle_error: (Response response) -> untyped

    def handle_response: (Response response) -> untyped

    def result: ((Response | Array[Response]) response) -> untyped

    def response_array: (Array[Response] array_response) -> untyped
  end

  class Request
    @connection: untyped

    def self.send_request: (TogglRb::Connection connection, Symbol request_method, String resource_path, ?untyped? body, ?Hash[untyped, untyped] request_options) -> untyped

    def initialize: (TogglRb::Connection connection) -> void

    def execute: () -> TogglRb::Response

    def send_request: (Symbol request_method, String resource_path, ?untyped? body) -> TogglRb::Response

    def delete?: () -> bool

    def get_all?: () -> bool

    def result_format: () -> Symbol

    def request_options: () -> Hash[Symbol, untyped]

    def result_class: () -> _FromAPIBody?

    def result_option: () -> Symbol?

    attr_accessor params: (TogglRb::Params | TogglRb::JSONPatch)

    attr_accessor request_method: Symbol

    attr_accessor resource_path: String

    attr_writer request_options: Hash[Symbol, untyped]

    private

    def build_params: (TogglRb::Params | TogglRb::JSONPatch | Hash[untyped, untyped]  | nil) -> (TogglRb::Params | TogglRb::JSONPatch)

    def log_request: () -> void

    attr_reader connection: TogglRb::Connection
  end
end
