module TogglRb
  class Response
    @farady_response: untyped

    @body_json: (Hash[untyped, untyped] | Array[untyped])

    extend Forwardable

    NEXT_ROW_NUMBER_HEADER: "x-next-row-number"

    def initialize: (untyped farady_response) -> void

    def body_json: () -> (Hash[untyped, untyped] | Array[untyped])

    def more?: () -> bool

    def success?: () -> bool

    def next_row_number: () -> String?

    attr_accessor request: TogglRb::Request

    def next_page_request: () -> TogglRb::Request
  end
end
