module TogglRb
  module Reports
    class Detailed
      include TogglRb::EndpointDSL
      include TogglRb::RequestHelpers
      extend EndpointDSL::ClassMethods

      def search_time_entries: (untyped workspace_id, ?::Hash[untyped, untyped] params) -> untyped

      private

      def connection: () -> untyped
    end
  end
end
