---
http_interactions:
- request:
    method: put
    uri: https://api.track.toggl.com/api/v9/me
    body:
      encoding: UTF-8
      string: '{"beginning_of_week":0,"country_id":40,"fullname":"Updated withPATCH","timezone":"Europe/London"}'
    headers:
      User-Agent:
      - Faraday v2.9.0
      Authorization:
      - Basic <TOGGL_BASIC_AUTH>
      Content-Type:
      - application/json
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      server:
      - nginx
      date:
      - Tue, 23 Apr 2024 15:55:01 GMT
      content-type:
      - application/json; charset=utf-8
      content-length:
      - '571'
      cache-control:
      - no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
      x-toggl-request-id:
      - 5d2aaf19-417e-49f0-98a9-b618ab620c9c
      x-service-level:
      - GREEN
      instance:
      - track-public-api-proxy-f666f86df-ng2v4
      strict-transport-security:
      - max-age=15552000; includeSubDomains
      x-frame-options:
      - SAMEORIGIN
      x-content-type-options:
      - nosniff
      x-we-are-hiring:
      - https://toggl.com/jobs/
      x-request-id:
      - 50aff17551c86f37d9414ec2221aae25
      referrer-policy:
      - strict-origin-when-cross-origin
      via:
      - 1.1 google
      alt-svc:
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    body:
      encoding: UTF-8
      string: '{"id":10658406,"api_token":"<TOGGL_API_TOKEN>","email":"<TOGGL_USER_EMAIL>","fullname":"Updated
        withPATCH","timezone":"Europe/London","toggl_accounts_id":"AXnZJWgbGgyrdT6a9tcR6X","toggl_accounts_updated_at":"2024-04-23T15:55:01.004574Z","default_workspace_id":<TOGGL_WORKSPACE_ID>,"beginning_of_week":0,"image_url":"https://assets.track.toggl.com/images/profile.png","created_at":"2024-04-09T03:12:46.676852Z","updated_at":"2024-04-23T15:54:40.151498Z","openid_email":null,"openid_enabled":false,"country_id":40,"has_password":true,"at":"2024-04-23T15:55:00.906289Z"}'
  recorded_at: Tue, 23 Apr 2024 15:55:01 GMT
recorded_with: VCR 6.2.0
