type string_or_int = String | Integer

type attributes = ::Hash[untyped,untyped]

interface _FromAPIBody
  def build_from_api_body: (Array[untyped] | Hash[untyped, untyped] | String) -> untyped

  def nil?: () -> bool
end

module TogglRb
  self.@config: TogglRb::Config

  self.@client: TogglRb::Client

  class Error < StandardError
  end

  def self.debug_logging?: () -> bool

  def self.config: () -> TogglRb::Config

  def self.client: () -> TogglRb::Client

  def self.operation: (?Array[Hash[String, (String|Array[untyped])]] operations) -> TogglRb::JSONPatch
end
